### PR TITLE
feat(cli): add timeout check for `demo` cmd

### PR DESCRIPTION
**Pull request by lizzy-0323**

### CODE REVIEW

**Review by powerfooI — COMMENTED** [review]
LGTM，but how to customize timeout duration?

**Comment by lizzy-0323** [comment]
> LGTM，but how to customize timeout duration?

In my design, it's `cmd.AddCommand(demo.NewCmd(0))`, and if the timeoutDuration set to 0, then using the defaultTimeoutDuration(30minutes).

**Comment by lizzy-0323** [comment]
After discussion, decide to use timeout duration as a flag, which is  available for users to alter

**Review by powerfooI — APPROVED** [review]
LGTM

**Pull request merged**
